name: Add New Domain

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "The new domain (after the '@')"
        required: true
        default: ''
      title:
        description: "The formal name of the institute ('Massachusetts Institute of Technology' for MIT)"
        required: true
        default: ''

jobs:
  update:
    name: Add New Domain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.16"

      - name: Install
        run: yarn --frozen-lockfile
        
      - name: Build
        run: yarn build

      - name: Run yarn open pr command
        run: yarn open:pr ${{ github.event.inputs.domain }} "${{ github.event.inputs.title }}"
      
      - name: Commit changes
        uses: tabnine/git-auto-commit-action@v4
        with:
          commit_message: [Bot] Add ${{ github.event.inputs.domain }}
